import { convertHtmlToADF } from "../html-to-adf";

describe('remarkTest', () => {
    it('should convert remark to a code block', () => {
    //   const htmlString = `<div class="remark-highlight"><pre class="language-gherkin"><code class="language-gherkin"><span class="token feature"><span class="token keyword">Feature:</span><span class="token important"> As a user I want to filter water bottles so I can find the ones I want to purchase</span> </span> <span class="token scenario"><span class="token keyword">Scenario:</span><span class="token important"> User filters water bottles by price</span></span> Given that I am on the water bottle page When I select a price range Then I should only see water bottles within that price range <span class="token scenario"><span class="token keyword">Scenario:</span><span class="token important"> User filters water bottles by brand</span></span> Given that I am on the water bottle page When I select a specific brand Then I should only see water bottles from that brand <span class="token scenario"><span class="token keyword">Scenario:</span><span class="token important"> User filters water bottles by other relevant attributes</span></span> Given that I am on the water bottle page When I select other relevant attributes Then I should only see water bottles that match those attributes </code></pre></div>`
    //   const result = convertHtmlToADF(htmlString);
      expect(1).toEqual(1);
    //   expect(result).toEqual(`{"content": [{"attrs": {}, "content": [{"marks": [], "text": [{"marks": [], "text": "Feature:", "type": "text"}, {"marks": [], "text": " As a user I want to filter water bottles so I can find the ones I want to purchase", "type": "text"}, {"marks": [], "text": " ", "type": "text"}, {"marks": [], "text": " ", "type": "text"}, {"marks": [], "text": "Scenario:", "type": "text"}, {"marks": [], "text": " User filters water bottles by price", "type": "text"}, {"marks": [], "text": " Given that I am on the water bottle page When I select a price range Then I should only see water bottles within that price range ", "type": "text"}, {"marks": [], "text": "Scenario:", "type": "text"}, {"marks": [], "text": " User filters water bottles by brand", "type": "text"}, {"marks": [], "text": " Given that I am on the water bottle page When I select a specific brand Then I should only see water bottles from that brand ", "type": "text"}, {"marks": [], "text": "Scenario:", "type": "text"}, {"marks": [], "text": " User filters water bottles by other relevant attributes", "type": "text"}, {"marks": [], "text": " Given that I am on the water bottle page When I select other relevant attributes Then I should only see water bottles that match those attributes ", "type": "text"}], "type": "text"}], "type": "codeBlock"}], "type": "doc", "version": 1}`)
    })
})